-- ---------------------------------------------------------------------------
-- V13 — customer-defined workflows.
--
-- Until now a workflow had to be a Java class compiled into the server, so the
-- durable engine (and everything built on it: deterministic replay, divergence
-- healing, exactly-once side effects) was unreachable for anyone who could not
-- fork and redeploy. A definition is a declarative graph of HTTP steps owned by
-- a developer, which the engine interprets.
--
-- Definitions are immutable per version. Starting a run pins the version it was
-- started with, so a later edit can never change how an in-flight execution
-- replays — the property the whole engine depends on.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS workflow_definitions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id  VARCHAR(64)  NOT NULL REFERENCES developers (id),
    name          VARCHAR(120) NOT NULL,
    version       INT          NOT NULL,
    spec_json     TEXT         NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_workflow_def_version UNIQUE (developer_id, name, version)
);

CREATE INDEX IF NOT EXISTS idx_workflow_def_owner
    ON workflow_definitions (developer_id, name, version DESC);
