-- Continuum durable execution engine — initial schema.
-- Four pillars: the immutable event log, the workflow projection, the durable
-- task queues, and the transactional outbox.

-- ---------------------------------------------------------------------------
-- Workflow instances: mutable projection of each execution (source of truth is
-- the event log, but this row makes status/queries cheap).
-- ---------------------------------------------------------------------------
CREATE TABLE workflow_instances (
    workflow_id       VARCHAR(64) PRIMARY KEY,
    workflow_type     VARCHAR(200) NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    input             TEXT,
    result            TEXT,
    error             TEXT,
    current_sequence  BIGINT       NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_instances_status ON workflow_instances (status);

-- ---------------------------------------------------------------------------
-- Workflow events: append-only log. (workflow_id, sequence_number) gives a
-- total order per workflow, which is what makes deterministic replay possible.
-- ---------------------------------------------------------------------------
CREATE TABLE workflow_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id     VARCHAR(64) NOT NULL,
    sequence_number BIGINT      NOT NULL,
    event_type      VARCHAR(40) NOT NULL,
    payload         TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_workflow_event_seq UNIQUE (workflow_id, sequence_number)
);
CREATE INDEX idx_events_workflow ON workflow_events (workflow_id);

-- ---------------------------------------------------------------------------
-- Activity tasks: the durable queue of non-deterministic work. Claimed with
-- FOR UPDATE SKIP LOCKED; recovered via the visibility timeout (locked_until).
-- ---------------------------------------------------------------------------
CREATE TABLE activity_tasks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id     VARCHAR(64)  NOT NULL,
    activity_type   VARCHAR(200) NOT NULL,
    sequence_number BIGINT       NOT NULL,
    input           TEXT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    retry_count     INTEGER      NOT NULL DEFAULT 0,
    max_attempts    INTEGER      NOT NULL DEFAULT 1,
    timeout_seconds INTEGER      NOT NULL DEFAULT 30,
    idempotency_key VARCHAR(128) NOT NULL,
    visible_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    locked_until    TIMESTAMPTZ,
    locked_by       VARCHAR(64),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_activity_task_seq UNIQUE (workflow_id, sequence_number)
);
CREATE INDEX idx_activity_claim ON activity_tasks (status, visible_at);
CREATE INDEX idx_activity_workflow ON activity_tasks (workflow_id);

-- ---------------------------------------------------------------------------
-- Workflow tasks: queue of pending deterministic decisions (start, or wake on
-- activity completion). Re-running a decision is always safe (pure replay).
-- ---------------------------------------------------------------------------
CREATE TABLE workflow_tasks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id  VARCHAR(64) NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    visible_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked_until TIMESTAMPTZ,
    locked_by    VARCHAR(64),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_workflow_task_claim ON workflow_tasks (status, visible_at);

-- ---------------------------------------------------------------------------
-- Outbox: external-message intents written atomically with the event log.
-- Unique idempotency_key guarantees at-most-once delivery.
-- ---------------------------------------------------------------------------
CREATE TABLE outbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id     VARCHAR(64),
    destination     VARCHAR(100) NOT NULL,
    event_type      VARCHAR(100) NOT NULL,
    payload         TEXT,
    idempotency_key VARCHAR(160) NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    attempts        INTEGER      NOT NULL DEFAULT 0,
    visible_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_error      TEXT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    dispatched_at   TIMESTAMPTZ,
    CONSTRAINT uq_outbox_idempotency UNIQUE (idempotency_key)
);
CREATE INDEX idx_outbox_status ON outbox (status, visible_at);

-- ---------------------------------------------------------------------------
-- LLM cost records: per-call token/cost accounting, deduped by idempotency key.
-- ---------------------------------------------------------------------------
CREATE TABLE llm_cost_records (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id       VARCHAR(64)  NOT NULL,
    idempotency_key   VARCHAR(128) NOT NULL,
    provider          VARCHAR(40)  NOT NULL,
    model             VARCHAR(100),
    prompt_tokens     INTEGER      NOT NULL DEFAULT 0,
    completion_tokens INTEGER      NOT NULL DEFAULT 0,
    estimated_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_cost_idempotency UNIQUE (idempotency_key)
);
CREATE INDEX idx_cost_workflow ON llm_cost_records (workflow_id);
