-- Continuum V2 — AI Reliability Research Extensions.
-- Purely additive: no V1 tables are altered. All new behavior is opt-in.

-- Extension 1 — Semantic Replay Verification reports.
CREATE TABLE replay_verification_reports (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id       VARCHAR(64)  NOT NULL,
    command_seq       BIGINT       NOT NULL,
    activity_type     VARCHAR(200) NOT NULL,
    historical_output TEXT,
    fresh_output      TEXT,
    fresh_provider    VARCHAR(40),
    similarity_score  DOUBLE PRECISION NOT NULL DEFAULT 0,
    intent_score      DOUBLE PRECISION NOT NULL DEFAULT 0,
    tool_score        DOUBLE PRECISION NOT NULL DEFAULT 0,
    structured_score  DOUBLE PRECISION NOT NULL DEFAULT 0,
    constraint_score  DOUBLE PRECISION NOT NULL DEFAULT 0,
    overall_score     DOUBLE PRECISION NOT NULL DEFAULT 0,
    passed            BOOLEAN      NOT NULL DEFAULT FALSE,
    method            VARCHAR(40),
    explanation       TEXT,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_rvr_workflow ON replay_verification_reports (workflow_id);
CREATE INDEX idx_rvr_created ON replay_verification_reports (created_at);

-- Extension 2 — measured provider runtime statistics + routing decisions.
CREATE TABLE provider_stats (
    provider          VARCHAR(40) PRIMARY KEY,
    calls             BIGINT NOT NULL DEFAULT 0,
    successes         BIGINT NOT NULL DEFAULT 0,
    failures          BIGINT NOT NULL DEFAULT 0,
    total_latency_ms  BIGINT NOT NULL DEFAULT 0,
    prompt_tokens     BIGINT NOT NULL DEFAULT 0,
    completion_tokens BIGINT NOT NULL DEFAULT 0,
    total_cost_usd    DOUBLE PRECISION NOT NULL DEFAULT 0,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE routing_decisions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id     VARCHAR(64),
    mode            VARCHAR(20) NOT NULL,
    complexity      DOUBLE PRECISION NOT NULL DEFAULT 0,
    chosen_provider VARCHAR(40),
    chain           VARCHAR(200),
    scores_json     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_routing_workflow ON routing_decisions (workflow_id);
CREATE INDEX idx_routing_created ON routing_decisions (created_at);

-- Extension 3 — AI chaos injection events.
CREATE TABLE ai_chaos_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id  VARCHAR(64),
    failure_type VARCHAR(30) NOT NULL,
    command_seq  BIGINT,
    detail       TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_aichaos_workflow ON ai_chaos_events (workflow_id);
CREATE INDEX idx_aichaos_type ON ai_chaos_events (failure_type);

-- Extension 5 — hierarchical memory store.
CREATE TABLE memory_entries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope            VARCHAR(128) NOT NULL,
    tier             VARCHAR(20)  NOT NULL,
    content          TEXT         NOT NULL,
    summary          TEXT,
    salience         DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    access_count     BIGINT       NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_accessed_at TIMESTAMPTZ
);
CREATE INDEX idx_memory_scope ON memory_entries (scope);
CREATE INDEX idx_memory_tier ON memory_entries (scope, tier);
