-- Continuum V3 — Developer AI Infrastructure Gateway.
-- Purely additive: no existing table is altered. All new behavior is opt-in and
-- gated behind authentication on /api/gateway/** only.

-- Feature 2 — developers & Continuum API keys (hashed, never plaintext).
CREATE TABLE developers (
    id         VARCHAR(64) PRIMARY KEY,
    name       VARCHAR(200) NOT NULL,
    email      VARCHAR(200),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE developer_api_keys (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id VARCHAR(64)  NOT NULL,
    key_prefix   VARCHAR(32)  NOT NULL,
    hashed_key   VARCHAR(128) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    revoked_at   TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ
);
CREATE INDEX idx_apikey_prefix ON developer_api_keys (key_prefix);

-- Feature 3 — developer provider keys (AES-256-GCM encrypted at rest).
CREATE TABLE developer_provider_credentials (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id     VARCHAR(64) NOT NULL,
    provider         VARCHAR(40) NOT NULL,
    encrypted_secret TEXT        NOT NULL,
    key_version      INTEGER     NOT NULL DEFAULT 1,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_dev_provider UNIQUE (developer_id, provider)
);

-- Features 6 & 7 — model registry, lifecycle, capabilities.
CREATE TABLE models (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider          VARCHAR(40)  NOT NULL,
    model_name        VARCHAR(120) NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    context_window    INTEGER      NOT NULL DEFAULT 0,
    capabilities_json TEXT,
    pricing_json      TEXT,
    last_checked_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_model UNIQUE (provider, model_name)
);
CREATE INDEX idx_models_status ON models (status);

-- Feature 5 — per-(provider,model) health for model-level fallback.
CREATE TABLE provider_model_health (
    id               VARCHAR(180) PRIMARY KEY,
    provider         VARCHAR(40)  NOT NULL,
    model_name       VARCHAR(120) NOT NULL,
    calls            BIGINT       NOT NULL DEFAULT 0,
    failures         BIGINT       NOT NULL DEFAULT 0,
    total_latency_ms BIGINT       NOT NULL DEFAULT 0,
    last_error       TEXT,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Feature 8 — gateway request observability.
CREATE TABLE gateway_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id    VARCHAR(64),
    requested_model VARCHAR(120),
    chosen_provider VARCHAR(40),
    chosen_model    VARCHAR(120),
    complexity      DOUBLE PRECISION NOT NULL DEFAULT 0,
    routing_reason  TEXT,
    latency_ms      BIGINT  NOT NULL DEFAULT 0,
    tokens          INTEGER NOT NULL DEFAULT 0,
    cost_usd        DOUBLE PRECISION NOT NULL DEFAULT 0,
    success         BOOLEAN NOT NULL DEFAULT FALSE,
    failover_count  INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_gwreq_dev ON gateway_requests (developer_id);
CREATE INDEX idx_gwreq_created ON gateway_requests (created_at);
