-- The model catalogue: what each provider lists, what was verified by a test
-- call, what went missing and what replaced it. Additive: existing rows keep
-- their status and gain the new facts on the next check.

ALTER TABLE models ADD COLUMN IF NOT EXISTS kind                VARCHAR(24);
ALTER TABLE models ADD COLUMN IF NOT EXISTS display_name        VARCHAR(160);
ALTER TABLE models ADD COLUMN IF NOT EXISTS description         TEXT;
ALTER TABLE models ADD COLUMN IF NOT EXISTS note                TEXT;
ALTER TABLE models ADD COLUMN IF NOT EXISTS max_output_tokens   INTEGER NOT NULL DEFAULT 0;
ALTER TABLE models ADD COLUMN IF NOT EXISTS provider_created_at BIGINT  NOT NULL DEFAULT 0;
ALTER TABLE models ADD COLUMN IF NOT EXISTS preview             BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE models ADD COLUMN IF NOT EXISTS status_reason       TEXT;
ALTER TABLE models ADD COLUMN IF NOT EXISTS verified_at         TIMESTAMPTZ;
ALTER TABLE models ADD COLUMN IF NOT EXISTS probe_outcome       VARCHAR(24);
ALTER TABLE models ADD COLUMN IF NOT EXISTS probed_at           TIMESTAMPTZ;
ALTER TABLE models ADD COLUMN IF NOT EXISTS limits_json         TEXT;
ALTER TABLE models ADD COLUMN IF NOT EXISTS miss_count          INTEGER NOT NULL DEFAULT 0;
ALTER TABLE models ADD COLUMN IF NOT EXISTS missing_since       TIMESTAMPTZ;
ALTER TABLE models ADD COLUMN IF NOT EXISTS retired_at          TIMESTAMPTZ;
ALTER TABLE models ADD COLUMN IF NOT EXISTS replaced_by         VARCHAR(120);
ALTER TABLE models ADD COLUMN IF NOT EXISTS first_seen_at       TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE models ADD COLUMN IF NOT EXISTS source              VARCHAR(16) NOT NULL DEFAULT 'seed';

-- Per provider: when its list was last read, what it chose as the default, and
-- any model an operator pinned.
CREATE TABLE IF NOT EXISTS model_provider_state (
    provider         VARCHAR(40) PRIMARY KEY,
    last_list_ok_at  TIMESTAMPTZ,
    last_attempt_at  TIMESTAMPTZ,
    last_error       TEXT,
    listed_count     INTEGER NOT NULL DEFAULT 0,
    default_model    VARCHAR(120),
    pinned_model     VARCHAR(120),
    last_confirm_at  TIMESTAMPTZ
);

-- One row per check, scheduled or pressed, with what it cost.
CREATE TABLE IF NOT EXISTS model_check_runs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_kind  VARCHAR(20) NOT NULL,
    requested_by  VARCHAR(64),
    started_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at   TIMESTAMPTZ,
    outcome       VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
    summary       TEXT,
    list_calls    INTEGER NOT NULL DEFAULT 0,
    probe_calls   INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_model_check_runs_started ON model_check_runs (started_at DESC);

-- What changed, in order: added, verified, missing, retired, replaced.
CREATE TABLE IF NOT EXISTS model_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider    VARCHAR(40) NOT NULL,
    model_name  VARCHAR(120),
    type        VARCHAR(24) NOT NULL,
    detail      TEXT,
    run_id      BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_model_events_created ON model_events (created_at DESC);

-- One check at a time, across every instance of the backend.
CREATE TABLE IF NOT EXISTS model_check_lease (
    id           INTEGER PRIMARY KEY,
    holder       VARCHAR(64),
    acquired_at  TIMESTAMPTZ
);
INSERT INTO model_check_lease (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
