-- A decision that keeps throwing used to be retried every 60 seconds forever.
-- Now each claim counts, failures back off, and after a limit the decision is
-- parked (status FAILED) with its error, until someone resumes the workflow.
ALTER TABLE workflow_tasks ADD COLUMN IF NOT EXISTS attempts   INTEGER     NOT NULL DEFAULT 0;
ALTER TABLE workflow_tasks ADD COLUMN IF NOT EXISTS last_error TEXT;
ALTER TABLE workflow_tasks ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS idx_workflow_task_workflow ON workflow_tasks (workflow_id, status);

-- What each retention pass removed, for the operator console.
CREATE TABLE IF NOT EXISTS retention_runs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger     VARCHAR(20)  NOT NULL,
    started_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    deleted     TEXT,
    error       TEXT
);
