-- Webhook endpoints: where an account wants to hear about its workflows.
-- Deliveries go through the transactional outbox, so an event is enqueued in
-- the same transaction as the change it reports and delivered once per
-- endpoint, signed, with a stable idempotency key.
CREATE TABLE IF NOT EXISTS webhook_endpoints (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id     VARCHAR(64)  NOT NULL,
    url              VARCHAR(2000) NOT NULL,
    description      VARCHAR(200),
    secret_encrypted TEXT         NOT NULL,
    events           VARCHAR(500) NOT NULL,
    enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_webhook_endpoints_dev ON webhook_endpoints (developer_id);

-- One row per delivery attempt: what was sent where, and what came back.
CREATE TABLE IF NOT EXISTS webhook_deliveries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint_id  BIGINT       NOT NULL,
    outbox_id    BIGINT,
    event        VARCHAR(60)  NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    attempt      INTEGER      NOT NULL,
    status_code  INTEGER,
    error        TEXT,
    duration_ms  BIGINT       NOT NULL DEFAULT 0,
    attempted_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_endpoint ON webhook_deliveries (endpoint_id, attempted_at DESC);
