-- Continuum V4 feature — Autopilot (autonomous control plane).
-- Strictly additive: no existing table is altered. Autopilot is opt-in per
-- developer and DISABLED by default, so with it off the runtime is unchanged.

-- Opt-in state + profile + active/canary pointers.
CREATE TABLE autopilot_config (
    developer_id     VARCHAR(64) PRIMARY KEY,
    enabled          BOOLEAN     NOT NULL DEFAULT FALSE,
    auto_apply       BOOLEAN     NOT NULL DEFAULT FALSE,
    mode             VARCHAR(20) NOT NULL DEFAULT 'BALANCED',
    profile_json     TEXT,
    active_bundle_id BIGINT,
    canary_bundle_id BIGINT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Versioned, content-immutable policy bundles (history + rollback targets).
CREATE TABLE autopilot_policy_bundles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id VARCHAR(64) NOT NULL,
    version      INTEGER     NOT NULL,
    status       VARCHAR(20) NOT NULL,
    bundle_json  TEXT        NOT NULL,
    parent_id    BIGINT,
    source       VARCHAR(40),
    notes        TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_apbundle_dev ON autopilot_policy_bundles (developer_id);
CREATE INDEX idx_apbundle_status ON autopilot_policy_bundles (developer_id, status);

-- Periodic telemetry snapshots observed by the loop.
CREATE TABLE autopilot_telemetry (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id  VARCHAR(64) NOT NULL,
    snapshot_json TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_aptel_dev ON autopilot_telemetry (developer_id, created_at);

-- Auditable decisions.
CREATE TABLE autopilot_decisions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id VARCHAR(64) NOT NULL,
    type         VARCHAR(30) NOT NULL,
    summary      TEXT,
    detail_json  TEXT,
    bundle_id    BIGINT,
    confidence   DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_apdecision_dev ON autopilot_decisions (developer_id, created_at);

-- Developer-approvable recommendations (read-only mode).
CREATE TABLE autopilot_recommendations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id       VARCHAR(64)  NOT NULL,
    title              VARCHAR(200) NOT NULL,
    rationale          TEXT,
    impact             VARCHAR(200),
    proposed_bundle_id BIGINT,
    status             VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    confidence         DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_aprec_dev ON autopilot_recommendations (developer_id, status);

-- Canary runs comparing candidate vs baseline bundle.
CREATE TABLE autopilot_canary_runs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id        VARCHAR(64) NOT NULL,
    candidate_bundle_id BIGINT      NOT NULL,
    baseline_bundle_id  BIGINT,
    percentage          INTEGER     NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
    metrics_json        TEXT,
    started_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at            TIMESTAMPTZ
);
CREATE INDEX idx_apcanary_dev ON autopilot_canary_runs (developer_id, status);

-- Rollback events (auto or manual).
CREATE TABLE autopilot_rollbacks (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id   VARCHAR(64) NOT NULL,
    from_bundle_id BIGINT,
    to_bundle_id   BIGINT,
    reason         TEXT,
    automatic      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_aprollback_dev ON autopilot_rollbacks (developer_id, created_at);

-- Optional feedback signal.
CREATE TABLE autopilot_feedback (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id VARCHAR(64) NOT NULL,
    request_ref  VARCHAR(120),
    score        DOUBLE PRECISION NOT NULL DEFAULT 0,
    comment      TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_apfeedback_dev ON autopilot_feedback (developer_id, created_at);

-- Attributes a gateway request to the bundle that served it (canary metrics)
-- WITHOUT touching the existing gateway_requests table.
CREATE TABLE autopilot_request_labels (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gateway_request_id BIGINT,
    developer_id       VARCHAR(64) NOT NULL,
    bundle_id          BIGINT      NOT NULL,
    is_canary          BOOLEAN     NOT NULL DEFAULT FALSE,
    success            BOOLEAN     NOT NULL DEFAULT TRUE,
    latency_ms         BIGINT      NOT NULL DEFAULT 0,
    cost_usd           DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_aplabel_bundle ON autopilot_request_labels (bundle_id);
